### ISSUE TITLE
ck37r package errors from ML-R at UCSF

### ISSUE THREAD

**Issue by EastBayEv** [ck37/ck37r#1]
Error: 'categoricals_to_factors' is not an exported object from 'namespace:ck37r'

and

Error: 'factors_to_indicators' is not an exported object from 'namespace:ck37r'

For some people, categoricals_to_factors worked but factors_to_indicators did not. For others, categoricals_to_factors did not work at all. model.matrix was the workaround.

**Comment by ck37** [comment]
Those errors are due to using the old CRAN version rather than the updated GitHub version.
